export const currencyOptions = [
    { value: 'USD', label: 'US Dollar', countryCode: 'us' },
    { value: 'EUR', label: 'Euro', countryCode: 'eu' },
    { value: 'GBP', label: 'British Pound', countryCode: 'gb' },
    { value: 'INR', label: 'Indian Rupee', countryCode: 'in' },
    { value: 'JPY', label: 'Japanese Yen', countryCode: 'jp' },
    { value: 'CAD', label: 'Canadian Dollar', countryCode: 'ca' },
    { value: 'AUD', label: 'Australian Dollar', countryCode: 'au' },
    { value: 'CHF', label: 'Swiss Franc', countryCode: 'ch' },
    { value: 'CNY', label: 'Chinese Yuan', countryCode: 'cn' },
    { value: 'HKD', label: 'Hong Kong Dollar', countryCode: 'hk' },
    { value: 'SGD', label: 'Singapore Dollar', countryCode: 'sg' },
    { value: 'NZD', label: 'New Zealand Dollar', countryCode: 'nz' },
    { value: 'ZAR', label: 'South African Rand', countryCode: 'za' },
    { value: 'SEK', label: 'Swedish Krona', countryCode: 'se' },
    { value: 'NOK', label: 'Norwegian Krone', countryCode: 'no' },
    { value: 'DKK', label: 'Danish Krone', countryCode: 'dk' },
    { value: 'KRW', label: 'South Korean Won', countryCode: 'kr' },
    { value: 'THB', label: 'Thai Baht', countryCode: 'th' },
    { value: 'MXN', label: 'Mexican Peso', countryCode: 'mx' },
    { value: 'BRL', label: 'Brazilian Real', countryCode: 'br' },
    { value: 'RUB', label: 'Russian Ruble', countryCode: 'ru' },
    { value: 'IDR', label: 'Indonesian Rupiah', countryCode: 'id' },
    { value: 'PHP', label: 'Philippine Peso', countryCode: 'ph' },
    { value: 'MYR', label: 'Malaysian Ringgit', countryCode: 'my' },
    { value: 'TRY', label: 'Turkish Lira', countryCode: 'tr' },
    { value: 'SAR', label: 'Saudi Riyal', countryCode: 'sa' },
    { value: 'AED', label: 'UAE Dirham', countryCode: 'ae' },
  ];
  